from tkinter import *

root=Tk()
root.title("tkinter window")
root.geometry("400x700")
root.resizable(0,0)
title=Label(root,text="CALCULATOR!!!")
title.config(font=("",35))
title.place(relx=0.08,rely=0.20)
button=Button(root,text="ENTER THE NUMBERS :")
button.place(relx=0.05,rely=0.35)
ent=Entry()
ent.place(relx=0.40,rely=0.35)
#button=Button(root,text="enter the second number :")
#button.place(relx=0.09,rely=0.24)
#ent=Entry(root)
#ent.place(relx=0.35,rely=0.25)
button=Button(root,text="1")
button.place(relx=0.36,rely=0.55)
button=Button(root,text="2")
button.place(relx=0.36,rely=0.50)
button=Button(root,text="3")
button.place(relx=0.43,rely=0.50)
button=Button(root,text="4")
button.place(relx=0.50,rely=0.50)
button=Button(root,text="5")
button.place(relx=0.58,rely=0.50)
button=Button(root,text="6")
button.place(relx=0.36,rely=0.45)
button=Button(root,text="7")
button.place(relx=0.43,rely=0.45)
button=Button(root,text="8")
button.place(relx=0.50,rely=0.45)
button=Button(root,text="9")
button.place(relx=0.58,rely=0.45)
button=Button(root,text="+")
button.place(relx=0.43,rely=0.55)
button=Button(root,text="-")
button.place(relx=0.50,rely=0.55)
button=Button(root,text="*")
button.place(relx=0.58,rely=0.55)
button=Button(root,text="D")
button.place(relx=0.58,rely=0.60)
button=Button(root,text="/")
button.place(relx=0.50,rely=0.60)
button=Button(root,text="^")
button.place(relx=0.43,rely=0.60)
button=Button(root,text="0")
button.place(relx=0.36,rely=0.60)
button=Button(root,text="OFF")
#button.place(relx=0.70,rely=0.40)
#button=Button(root,text="ON")
button.place(relx=0.80,rely=0.40)
button=Button(root,text="=")
button.place(relx=0.65,rely=0.60)
button=Button(root,text="( ")
button.place(relx=0.65,rely=0.50)
button=Button(root,text=") ")
button.place(relx=0.65,rely=0.55)
button=Button(root,text="ON")
button.place(relx=0.65,rely=0.45)
#button=Button(root,text="OUTPUT")
#button.place(relx=0.26,rely=0.65)
#ent=Entry(root)
#ent.place(relx=0.45,rely=0.65)
root.mainloop()

